name: agriprofit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24
  - pandas>=2.1
  - scikit-learn>=1.3
  - statsmodels>=0.14
  - matplotlib>=3.7
  - plotly>=5.15
  - streamlit>=1.36
  - pip:
      - prophet
      - shap
